### ISSUE TITLE
only show in realtime

### ISSUE THREAD

**Issue by sing0730** [cmackay/google-analytics-plugin#36]
My stat only show in realtime.I cant see any information in app overview. I use following code to send.

analytics.sendAppView(title, null, null);

Thanks for your help!

**Comment by cmackay** [comment]
Because you are seeing the information in realtime, It appears everything is working properly. The analytics reporting data in the non-realtime areas is delayed. The Google Analytics docs go into more detail on this but just doing a quick search I found the following:

http://www.quora.com/How-lagged-is-the-reporting-of-Google-Analytics

Hope this helps.
