### ISSUE TITLE
analytics.enableAdvertisingIdCollection - Demoraphics

### ISSUE THREAD

**Issue by niroam** [cmackay/google-analytics-plugin#39]
Hi @cmackay 

Noobish question maybe - Have you tested this against the GA Demographics reporting ? I was trying to get that working by using the following code, i get all the success callbacks but in the GA console it keeps failing to validate the tracking code asking to add the one line of code which is what the method enableAdvertisingCollection in your plugin does.

Am i implimenting the calls incorrectly ?

var analytics = navigator.analytics;
// set the tracking id
analytics.setTrackingId('UA-XXXXX-X');
//
analytics.enableAdvertisingIdCollection(successCallback, errorCallback);
//
analytics.sendAppView('home', successCallback, errorCallback);

**Comment by cmackay** [comment]
I haven't used that feature and I am not sure how it works. Do you get a specific error message on the client? Also, do you see the appView event showing up in the console? If not, does it show up if you remove the enableAdvertisingIdCollection? I wish I could be more help but I haven't used the enableAdvertisingIdCollection function. Let me know how it works out.

Thanks!

-Craig

**Comment by niroam** [comment]
Hi Craig,

I'm not getting any error messages and the appView event comes up on the console so as far as i know everything is working ok. my understanding is that enableAdervisingId starts sending the clients IDFA that allows google to report on any demographics they have for the IDFA collected elsewhere... I was hopin to show some stats on Age/Gender for usage on the app i'm creating and yours was the only phonegap plugin i saw that enabled the IDFA collection on the SDK as per the code provided by google so was hoping it would do the trick! ...

Will keep testing and post any results here - thanks!

Niro

**Comment by cmackay** [comment]
Hi Niro,

Thanks for the info. I think this is related to the libAdIdAccess library which is no longer configured in the plugin.xml. The problem is that when this has been configured as part of the plugin, it can cause app store submissions to fail to apple. More details are in some of the closed issues where this has caused problems for users. We haven't found a good way to conditionally enable this in the plugin.xml so that only the users needing this feature will have it enabled. If you have any suggestions, please let me know. If you want to try to enable this feature in your local version. I would recommend checking out the release that removed this functionality and you can probably add this back to your local version and it might work. 

https://github.com/cmackay/google-analytics-plugin/commit/dcf052f322490f900483ecea425f731a69e92621

Let me know if you have any ideas for better supporting this. For now I am going to remove the function from the readme api.

Thanks!

-Craig

**Comment by andreapozzetti** [comment]
@cmackay 
hi, i ask you a recap.
i need the demographics functions.
in the current version of the plugin, demographics function are dislabled for iOS and works for Android? Or are disabled for both?

I want to enable this functionalities for iOS (and Android if they are disabled). i should reenable the parts of the plugin that you removed in a previous version?
thanks a lot

**Comment by cmackay** [comment]
It is disabled in iOS and enabled in Android. There have been multiple issues submitted in the past where users have reported thats apps were rejected when this was enabled. The majority of users do not use this feature so for that reason it makes more sense that this be disabled.

If you need this functionality, you will have to add back the changes from this commit:

**Comment by GitRubb** [comment]
can setIDFAEnabled be added back to master? Doesn't make sense to remove it from the plugin when it's the responsibility of the developer to check those IDFA questions during app submission.
