### ISSUE TITLE
IDFA

### ISSUE THREAD

**Issue by hassankhan** [cmackay/google-analytics-plugin#60]
I read through the issues, the only reason someone's app would get rejected on the App Store is if they hadn't ticked the correct boxes. Maybe it could be enabled with a warning on the README?

**Comment by cmackay** [comment]
My understanding of this is that for it to work the ios lib libAdIdAccess.a has to be linked (and the  Ad Framework support). When submitting the app, the app store detects that this lib is present and if a user has not configured idfa it causes a failed submission because the library is linked and not used. I don't know that there is a good solution to link this only when needed. The majority of users do not use IDFA. I do not want to inconvenience the majority of users for a feature that is not widely used. If this is no longer an issue with app store submissions and you would like to implement it along with helping by supporting any issues that are a result of adding it then I might consider pulling in this functionality.

Here is some more info:

https://code.google.com/p/analytics-issues/issues/detail?id=387
