### ISSUE TITLE
Invalid use of Google Play Services (+ a workround how to fix it)

### ISSUE THREAD

**Issue by Ziv-Barber** [cmackay/google-analytics-plugin#67]
On build.gradle:

Change:

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    ...
    compile "com.google.android.gms:play-services:+"
    // SUB-PROJECT DEPENDENCIES END
}

To:

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DDDEPENDENCIES START
    ...
    // compile "com.google.android.gms:play-services:+"
	compile "com.google.android.gms:play-services-analytics:+"
    // SUB-PROJECT DDDEPENDENCIES END
}

It's NOT possible to add ALL of Google Play Services.... so we must add only play-services-analytics.

**Comment by cmackay** [comment]
At one time It was possible and it was also the documented approach for including google play services but things do change. I appreciate the information you have provided.

It looks like this might need updating so that people don't have to manually edit the gradle file. https://github.com/cmackay/google-analytics-plugin/blob/master/plugin.xml#L83

I will make the change sometime later on and publish a new release.

Thanks!
